### ISSUE TITLE
Issue compiler

### ISSUE THREAD

**Issue by dan085** [jeffreyliu8/FlexBoxRadioGroup#2]
/Users/dverdugo/.gradle/caches/transforms-2/files-2.1/8d34e658e6b6a7e78556e724db458b7a/material-1.1.0/res/values/values.xml:2980:5-2987:23: AAPT: error: duplicate value for resource 'attr/checkedButton' with config ''.

**Comment by jeffreyliu8** [comment]
are you trying to compile this repo?

**Comment by jahawaioz** [comment]
Hi,
I had a same issue like 
**../../../../../.gradle/caches/transforms-2/files-2.1/901754ead44677ce821910b6beafc5f5/material-1.3.0-beta01/res/values/values.xml**
kindly help us

**Comment by jeffreyliu8** [comment]
will be fixed soon.
